### ISSUE TITLE
Unable to finish upgrade with upgrade.

### ISSUE THREAD

**Issue by bhgraham** [jenkinsci/rancher-plugin#15]
I have a job configured to upgrade and "Auto Confirm" selected.  When it runs it performs the upgrade but will not finish.

Rancher plugin version : 1.0.8-SNAPSHOT (private-12/14/2017 16:59-zhengyunlong)

Here is the jenkins log:
12:42:19 Deploy/Upgrade image[docker:id/cont:latest] to service [id/cont] to rancher environment [http://rancher.company.com:50070/v2-beta/projects/1a5]
12:42:19 Stack already exist. skip
12:42:19 Upgrading service instance
12:42:19 service submanage current state is active
12:42:29 waiting service state to be upgraded (timeout:10s)ERROR: Build step failed with exception
12:42:29 java.lang.RuntimeException: Some Error Happen statusCode 422 response: {"id":"1d087db0-97c6-4b01-be98-5f6151513324","type":"error","links":{},"actions":{},"status":422,"code":"ActionNotAvailable","message":null,"detail":null,"fieldName":"action","baseType":"error"}
12:42:29 	at jenkins.plugins.rancher.HttpClient.execute(HttpClient.java:72)
12:42:29 	at jenkins.plugins.rancher.HttpClient.post(HttpClient.java:47)
12:42:29 	at jenkins.plugins.rancher.RancherClient.finishUpgradeService(RancherClient.java:60)
12:42:29 	at jenkins.plugins.rancher.RancherBuilder.upgradeService(RancherBuilder.java:145)
12:42:29 	at jenkins.plugins.rancher.RancherBuilder.perform(RancherBuilder.java:93)
12:42:29 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
12:42:29 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:42:29 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
12:42:29 	at hudson.model.Build$BuildExecution.build(Build.java:206)
12:42:29 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
12:42:29 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
12:42:29 	at hudson.model.Run.execute(Run.java:1724)
12:42:29 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:42:29 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:42:29 	at hudson.model.Executor.run(Executor.java:421)
12:42:29 Build step 'Deploy/Upgrade Rancher Service' marked build as failure
12:42:29 Finished: FAILURE

**Comment by solocommand** [comment]
Same issue here. I just installed the rancher plugin on another server and it brought in the `1.0.8-SNAPSHOT (private-12/14/2017 16:59-zhengyunlong)` version. I don't see the issue on another server running `1.0.5`.

It looks like it's not waiting for the timeout to try and finish the upgrade, but rather immediately trying to call finish after sending the upgrade.

In my logs, the timeout appears to be 0s:
```
Deploy/Upgrade image[docker:ecsid.dkr.ecr.us-east-1.amazonaws.com/scontent-api:v5] to service [scontent/api] to rancher environment [https://rancher.company.io/v2-beta/projects/1a18]
Stack already exist. skip
Upgrading service instance
service api current state is active
waiting service state to be upgraded (timeout:0s)[Pipeline] }
// snip
GitHub has been notified of this commit’s build result

java.lang.RuntimeException: Some Error Happen statusCode 422 response: {"id":"0c8689fc-bba2-453a-a97c-58128cbdbc0e","type":"error","links":{},"actions":{},"status":422,"code":"ActionNotAvailable","message":null,"detail":null,"fieldName":"action","baseType":"error"}
```

Is it possible to install a specific version of the plugin in Jenkins, or can the release get rolled back to the last stable version?

**Comment by yunlzheng** [comment]
I will handle it now.

**Comment by yunlzheng** [comment]
@bhgraham @solocommand i just create a new release 1.0.8, please upgrade to the latest.

**Comment by solocommand** [comment]
@yunlzheng Hi, sorry for the delay. I have upgraded from `1.0.8-SNAPSHOT` to `1.0.8` but I'm still seeing the same issue. It's still immediately attempting to complete the upgrade, and not waiting for the service to be in a finishable state. Was there a new configuration or pipeline argument added for the timeout since 1.0.5?

```[Pipeline] { (Upgrade Container)
[Pipeline] rancher
Deploy/Upgrade image[docker:[awsid].dkr.ecr.us-east-1.amazonaws.com/scontent-api:v6] to service [scontent/api] to rancher environment [https://[company].io/v2-beta/projects/1a18]
Stack already exist. skip
Upgrading service instance
service api current state is active
waiting service state to be upgraded (timeout:0s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withDockerRegistry
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: Exception happened to wait service state with message:timeout
Finished: FAILURE
```

**Comment by yunlzheng** [comment]
@solocommand Please check the **timeout** properties, i think the current value is 0s

**Comment by yunlzheng** [comment]
@solocommand in the "advanced options"

**Comment by solocommand** [comment]
@yunlzheng I'm not sure where `advanced options` is as there doesn't seem to be a section for this plugin under Manage Jenkins > Configure System. But I was able to get it to work by adding the timeout parameter to my pipeline script.

Thanks!

**Comment by bhgraham** [comment]
I am unable to update as Jenkins still thinks the 1.0.8-SNAPSHOT (private-12/21/2017 09:12-zhengyunlong) version is the latest.  Could you up the version number to 1.0.9 so it will actually upgrade correctly again?

**Comment by yunlzheng** [comment]
@bhgraham the 1.0.9 version already release, can you can try it now.

**Comment by pkeshab** [comment]
I am using the latest version of rancher plugin, but while using this plugin in jenkins job I am getting the following error.  However manually I am able to run docker image in the rancher. Anyone have any idea on this please?
ERROR: Build step failed with exception
java.lang.RuntimeException: Some Error Happen statusCode 405 response: {"id":"e04a190b-fe2c-4010-b398-8f83d3efeb5e","type":"error","links":{},"actions":{},"status":405,"code":"Method not allowed","message":"Method not allowed","detail":null,"baseType":"error"}
	at jenkins.plugins.rancher.HttpClient.execute(HttpClient.java:72)
	at jenkins.plugins.rancher.HttpClient.post(HttpClient.java:42)
	at jenkins.plugins.rancher.RancherClient.createStack(RancherClient.java:47)
	at jenkins.plugins.rancher.RancherBuilder.createStack(RancherBuilder.java:240)
	at jenkins.plugins.rancher.RancherBuilder.getStack(RancherBuilder.java:233)

**Comment by solocommand** [comment]
@pkeshab Would be best to submit a new issue with details about your problem, as it's not directly related to this chain. When you do, make sure you also submit details about the jenkins, rancher-plugin, and rancher versions, as well as related pipeline or job configuration.

A 405 would seem to indicate that the plugin can't create the stack you're requesting. This is likely because of permissions on your API key, lack of an API key, or a version incompatibility.

**Comment by pkeshab** [comment]
@solocommand  Yes you are right. Initially tried with the endpoint V1 from rancher according to plugin suggestion but later I changed the end point to V2 and the issue was gone. Summing up, it was due to the version issue in the rancher end point. Thank you solocommand for the suggestions.

**Comment by PablloMatheus** [comment]
Hello, my jenkins with the installed rancher plugin is giving this error by taking the steps requested by jenkins

Connection fails with message : Some Error Happen statusCode 404 response: {"id":"b6f7dceb-f735-4565-a7a2-c6f082caf749","type":"error","links":{},"actions":{},"status":404,"code":"Not Found","message":"Not Found","detail":null,"baseType":"error"}
