### ISSUE TITLE
Leave ports as optional

### ISSUE THREAD

**Issue by danjesus** [jenkinsci/rancher-plugin#16]
Some containers do not have exposed ports so it is necessary to leave the ports as optional.

**Comment by danjesus** [comment]
@yunlzheng 1.0.8, but this behaviour only happening when i use rancher plugin inside a Jenkinsfile in a pipeline, in the old jenkins way works without ports.

**Comment by yunlzheng** [comment]
The reason why the plugin fails, is because when use Jenkinsfile without ports properties. the plugin will throw null point exception. the issue already fixed and will relase next version.
