### ISSUE TITLE
scheduling parameters are removed if plugin is used to upgrade service

### ISSUE THREAD

**Issue by MychauU** [jenkinsci/rancher-plugin#17]
![image](https://user-images.githubusercontent.com/26359661/35048520-a0ee904e-fb9d-11e7-9736-78b44c614475.png)

Information about scheduling from rancher service is removed after using jenkins job with plugin. (iamge shows  configuration with tells that service should work on specific host).
Work as intended if upgrade is started from rancher dashboard.

Expected effect: Should preserve configuration when upgrade job is started from jenkins.

**Comment by yunlzheng** [comment]
@MychauU Thanks for your feedback. At now you can try to schedule rule. And control the node schedule.

**Comment by MychauU** [comment]
![image](https://user-images.githubusercontent.com/26359661/35558057-50629d96-05a7-11e8-81b5-ae70efd0688b.png)
Jenkins shows new version but plugin can't be updated.
Even after reinstalling plugin, plugin isn't the newest

**Comment by yunlzheng** [comment]
Can you provide your current plugin now? I think that because the plugin setting format changed.

**Comment by MychauU** [comment]
1.0.8-SNAPSHOT (private-12/21/2017 09:12-zhengyunlong), I tried to deinstall and install again - it didn't work. I will try again maybe buy disabling part  (removing you plugin part )of jobs in jenkins

**Comment by andylhz-mojie** [comment]
the same problem

**Comment by zgc** [comment]
the same problem

**Comment by yunlzheng** [comment]
I just release a new version 1.0.11 to fixed this.  Thanks for your feedback.
