### ISSUE TITLE
Job Parameters do not work for plugin values

### ISSUE THREAD

**Issue by markpiersak** [jenkinsci/rancher-plugin#18]
![image](https://user-images.githubusercontent.com/31937131/35832942-bedf6366-0a94-11e8-8820-cc30da4fd6d5.png)
![image](https://user-images.githubusercontent.com/31937131/35832966-dd6531da-0a94-11e8-8dca-34a0ee4d2493.png)

ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Invalid uri '**${RANCHER_URL}**/projects/xxxxxx/stacks': incorrect path

**Comment by yunlzheng** [comment]
This is because the Endpoint properties not support environment variable. This will release next version.
