### ISSUE TITLE
Start First Always Fales

### ISSUE THREAD

**Issue by Jlaird** [jenkinsci/rancher-plugin#22]
There is no default value and I don't see a way to pass in an option to set  startFirst to true.
https://github.com/jenkinsci/rancher-plugin/blob/9f1386fc9d7d704ffe850a2a2621218c903d052d/src/main/java/jenkins/plugins/rancher/action/InServiceStrategy.java#L11

The logic below looks correct, if a port is set it would cause a confect if it's on the same server using start first. 
https://github.com/jenkinsci/rancher-plugin/blob/dac5143e5f10e3a6b7009afa4ac040199b3cb98d/src/main/java/jenkins/plugins/rancher/RancherBuilder.java#L155

**Comment by parin921996** [comment]
is there a way to use `startFirst` as variable in Jenkins  ? I want to set it as false.

**Comment by Jlaird** [comment]
Currently no, but if you set a port it will be set to false. Is there a reason why you would want it set to false?

**Comment by parin921996** [comment]
We have a stack which requires to be stopped before start otherwise service discovery is having trouble resolving IP.
