### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by ph4r5h4d** [jenkinsci/rancher-plugin#35]
I've got this error in jenkins log
I've tried putting unsigned ssl cert into java keystore and didn't work
I also tried with lets encrypt SSL and no matter what whenever i try to connect to rancher 2 i get this error.

Two questions: 
1- Does this plugin work with rancher 2?
2- Is there any workaround to get past this error.

**Comment by yunlzheng** [comment]
Sorry, this plugin not support rancher2 at this moment.
