### ISSUE TITLE
Start Before Stop

### ISSUE THREAD

**Issue by jbrinksmeier** [jenkinsci/rancher-plugin#41]
Hi there. Thanks a lot for the great work with this plugin. I'm a bit confused wether the feature implemented in PR #22 
is already available in a release or if one is planned? Or do I have to build the plugin myself if I need it? 

Best Regards,
Johannes

**Comment by yunlzheng** [comment]
The code already merged in master, i will make a release recently after test.

**Comment by yunlzheng** [comment]
release to 1.0.13
