### ISSUE TITLE
support build variables in all fields

### ISSUE THREAD

**Issue by raffaeleguidi** [jenkinsci/rancher-plugin#5]
Hi, I would like to suggest allowing build variables (and also, of course parameter values) for all fields - such as service, environment and target environment variables

**Comment by yunlzheng** [comment]
Looks cool, i will try to do that in next release.

**Comment by raffaeleguidi** [comment]
thanks, I volounteer for testing :)

**Comment by yunlzheng** [comment]
Sorry. i was too busy last month. The new version 1.0.7 already support this feature.

**Comment by raffaeleguidi** [comment]
awesome, thank you, I will test it out asap

**Comment by yunlzheng** [comment]
@raffaeleguidi Please upgrade to 1.0.7.1, there have some issue will break the process in 1.0.7 .
