### ISSUE TITLE
Warning when using with jenkins version 2.60.1

### ISSUE THREAD

**Issue by visarya** [jenkinsci/rancher-plugin#6]
I am unable to install plugin and get below warning with Jenkins version 2.60.1
Warning: the new version of this plugin claims to use a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details.

**Comment by yunlzheng** [comment]
Hi @visarya, i think the the issue is because the new version of this plugin use different setting format(Use Credentials store secret content instead of text). After install new version plugin please reconfiguration the old job use this plugin, and restart jenkins server.
